name: instagram_description_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Icons/appIcon.png"
  windows:
    generate: true
    image_path: "Icons/appIcon.png"
    icon_size: 128

flutter:
  uses-material-design: true
  fonts:
    - family:  IconicIcons
      fonts:
        - asset: fonts/IconicIcons.ttf
